package com.chromosundrift.bhima.dragonmind;

import com.chromosundrift.bhima.dragonmind.model.Config;
import com.chromosundrift.bhima.dragonmind.model.PixelPoint;
import com.chromosundrift.bhima.dragonmind.model.Segment;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;

/**
 * Generates a straight dragon model in a strict diamond grid, tapering from the bottom up.
 */
public class DragonBuilder {

    // TODO LHS
    // TODO finish tapering tail
    // TODO tail wiring
    // TODO neck (RHS only)
    // TODO exceptions
    // TODO test/verify

    private static final Logger logger = LoggerFactory.getLogger(DragonBuilder.class);

    private int xOrigin;
    private int yOrigin;
    int margin;
    private int gPanelNumber;
    private List<Segment> segments = new ArrayList<>();

    public DragonBuilder(int xOrigin, int yOrigin, int margin) {
        this.xOrigin = xOrigin;
        this.yOrigin = yOrigin;
        this.margin = margin;
    }

    public Config build() {
        // draw neck


        // TODO draw tapered tail panels

        // starting from panel 11, segments have progressively fewer rows
        // panel 11 has 10 rows in the rightmost column, then 9 for the rest


        Config c = new Config("Bhima model generated by DragonBuilder", "1.0");
        c.setPixelMap(segments);

        return c;
    }

    public SegmentBuilding addSegment(int nPanels, int pw, int ph) {
        return addSegment(nPanels, p -> true, pw, ph);
    }

    public SegmentBuilding addSegment(int nPanels, Function<PanelPoint, Boolean> includePoint, int pw, int ph) {

        int nLedX = 10;
        int nLedY = 10;
        int vStep = ph / nLedY;
        int hStep = pw / nLedX;
        int sNum = segments.size() + 1;
        Segment e = generateSegment(nPanels, xOrigin - (nPanels + gPanelNumber) * (pw + margin), yOrigin, pw, sNum, vStep, hStep, nLedX, nLedY);
        return new SegmentBuilding(e);
    }

    private Segment generateSegment(int nPanels, int x, int y, int pw, int sNum, int vStep, int hStep, int nLedX, int nLedY) {
        Segment s = new Segment();
        s.setName("generated segment " + sNum);

        // generate panels right to left
        for (int n = nPanels - 1; n >= 0; n--) {
            int xPos = x + (pw + margin) * n;
            s.addPixelPoints(generatePanel(xPos, y, nLedX, nLedY, hStep, vStep));
        }
        return s;
    }

    public List<PixelPoint> generatePanel(int x, int y, int nLedX, int nLedY, int dx, int dy) {
        ArrayList<PixelPoint> pps = new ArrayList<>();
        // start at the top right
        int pixelIndex = 0;
        int evenRowVerticalOffset = dy / 2;
        int stripIndex = 0;
        // start at top left
        for (int yy = 0; yy < nLedY; yy++) {

            // first zig - left to right

            for (int xx = 0; xx < nLedX; xx++) {
                boolean evenColumn = xx % 2 == gPanelNumber % 2;
                // y offset alternates each column, but is the same as the previous across panel boundaries
                int yOffset = evenColumn ? evenRowVerticalOffset : 0;
                PixelPoint pp = new PixelPoint(stripIndex, pixelIndex, x + dx * xx, y + yOffset + dy * yy);
                pps.add(pp);
                pixelIndex++;
            }
            yy++;

            // then zag - right to left

            for (int xx = nLedX - 1; xx >= 0; xx--) {
                boolean evenColumn = xx % 2 == gPanelNumber % 2;
                int yOffset = evenColumn ? evenRowVerticalOffset : 0;
                PixelPoint pp = new PixelPoint(stripIndex, pixelIndex, x + dx * xx, y + yOffset + dy * yy);
                pps.add(pp);
                pixelIndex++;
            }
        }
        gPanelNumber++;
        return pps;
    }

    /**
     * Represents an LED at the given x,y on a specific panel number.
     */
    public final class PanelPoint {
        public final int panelNumber;
        public final int x;
        public final int y;

        public PanelPoint(int panelNumber, int x, int y) {
            this.panelNumber = panelNumber;
            this.x = x;
            this.y = y;
        }
    }

    public final class SegmentBuilding {

        private Segment s;

        public SegmentBuilding(Segment segment) {
            this.s = segment;
        }

        public SegmentBuilding addSegment(int nPanels, int pw, int ph) {
            return addSegment(nPanels, p -> true, pw, ph);
        }

        public SegmentBuilding addSegment(int nPanels, Function<PanelPoint, Boolean> includePoint, int pw, int ph) {
            build();
            return DragonBuilder.this.addSegment(nPanels, includePoint, pw, ph);
        }

        public SegmentBuilding addPanel() {
            // TODO
            return this;
        }

        public void build() {
            if (s != null) {
                DragonBuilder.this.segments.add(s);
                s = null;
            }
        }

    }
}
